### ISSUE TITLE
Sequencing problems with PostgreSQL

### ISSUE THREAD

**Issue by albert-kam** [Ninja-Squad/DbSetup#67]
Hi guys, 

I have a working test suite, with all of the test classes using DbSetup the way it's described in the documentation.

Problem here is that i have a sequencing problems (my assumption) that only happen from time to time with postgresql with error message such as this one:

```
org.jdbi.v3.core.statement.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "appr_rule_pkey"
  Detail: Key (id)=(10) already exists. [statement:"INSERT INTO appr_rule (name, issuer_id, appr1_id, appr2_id, appr3_id, appr4_id, appr5_id, appr6_id, created_by_id) values (:name, :issuer_id, :appr1_id, :appr2_id, :appr3_id, :appr4_id, :appr5_id, :appr6_id, :created_by_id)", arguments:{positional:{}, named:{appr2_id:anana 5,issuer_id:anana 7,appr3_id:anana 4,appr1_id:anana 6,name:rule 2,created_by_id:myactor,appr5_id:anana 2,appr4_id:anana 3,appr6_id:anana 1}, finder:[]}]
```

After doing a bit of research, i found out that i may need to reset the sequences for each tables in dbsetup common operations in ```@Before```, so i did something like this:

```
public static final Operation INSERT_REFERENCE_DATA =
			sequenceOf(
    		sql("select setval('appr_rule_id_seq'::regclass, (select max(id) from only public.appr_rule))"),
            insertInto("t_user")
                .columns("id", "username", "displayname", "email", "roles", "password", "created_by_id")
                .values("root", "root", "initial user", "moonblade.wolf@gmail.com", "", "mypasssword", "")
                .values("myactor", "myactor", "myactor lar", "myactor@gmail.com", "admin", "mypasssword", "root")
                .build());
```

But this ends up with DbSetup error of:
```
com.ninja_squad.dbsetup.DbSetupRuntimeException: org.postgresql.util.PSQLException: A result was returned when none was expected.
	at com.ninja_squad.dbsetup.DbSetup.launch(DbSetup.java:123)
	at com.ninja_squad.dbsetup.DbSetupTracker.launchIfNecessary(DbSetupTracker.java:101)
	at test.TestUser.prepare(TestUser.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: org.postgresql.util.PSQLException: A result was returned when none was expected.
	at org.postgresql.jdbc.PgStatement.checkNoResultUpdate(PgStatement.java:257)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:247)
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
	at com.ninja_squad.dbsetup.operation.SqlOperation.execute(SqlOperation.java:64)
	at com.ninja_squad.dbsetup.operation.CompositeOperation.execute(CompositeOperation.java:92)
	at com.ninja_squad.dbsetup.operation.CompositeOperation.execute(CompositeOperation.java:92)
	at com.ninja_squad.dbsetup.DbSetup.launch(DbSetup.java:107)
	... 33 more
```

It seems like ```select setval``` returns something that DbSetup doesnt expect.

Any suggestions to deal with this situation would be greatly appreciated.

**Comment by gdemecki** [comment]
Exactly, It's a pity that `Operations.sql()` uses under the hood `executeUpdate(String sql)`. So no arbitrary selects are possible.

**Comment by albert-kam** [comment]
Hi again,

I solved this issue by not using SERIAL data type, and use this instead:
```
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
```

And i could do something like this to reset the counters for each method tests:
```
sql("ALTER TABLE appr_rule ALTER COLUMN id RESTART WITH 1")
```

And all is well after that, no more issues on conflicting ids.

Thank you.
