### ISSUE TITLE
insertInto with OffsetDateTime.MAX error

### ISSUE THREAD

**Issue by albert-kam** [Ninja-Squad/DbSetup#68]
When trying to setup db with postgresql timestampz column with OffsetDateTime.MAX results in error:

```
com.ninja_squad.dbsetup.DbSetupRuntimeException: org.postgresql.util.PSQLException: ERROR: time zone displacement out of range: "169104628-12-10 19:08:16-18 BC"
	at com.ninja_squad.dbsetup.DbSetup.launch(DbSetup.java:123)
	....
Caused by: org.postgresql.util.PSQLException: ERROR: time zone displacement out of range: "169104628-12-10 19:08:16-18 BC"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at com.ninja_squad.dbsetup.operation.Insert.execute(Insert.java:229)
	at com.ninja_squad.dbsetup.operation.CompositeOperation.execute(CompositeOperation.java:92)
	at com.ninja_squad.dbsetup.DbSetup.launch(DbSetup.java:107)
	... 28 more

```

The code snippet:

```
insertInto("brands")
	.columns("id", "code", "name", "valid_start", "valid_end")
	.values(3, "ON", "ONYX", now, du.nowUTC_plusDays(1))
	.values(4, "HW", "HUAWEI", now, OffsetDateTime.MAX) // errors here
	.build()
```
I wonder whether this is an issue with postgresql jdbc driver or the dbsetup ?

**Comment by jnizet** [comment]
DbSetup inserts the value using the TimestampBinder. See 
https://github.com/Ninja-Squad/DbSetup/blob/master/DbSetup-core/src/main/java/com/ninja_squad/dbsetup/bind/Binders.java#L371-L374. And the value is apparently not accepted by PostgreSQL (not sure exactly what the error message means, however). 

If your own code manages to insert such a large OffsetDateTime into the database, it probably does it in a different way.
You can use a Binder to insert the OffsetDateTime the way yu want to. Let's say for example you want to let the database driver deal with the OffsetDateTime all by itself by calling `setObject()` to bind it, you can use 

```
Binder objectBinder = (statement, param, value) -> statement.setObject(param, value);
insertInto("brands")
        .columns("id", "code", "name", "valid_start", "valid_end")
        .withBinder(objectBinder, "valid_end")
        ...
```

**Comment by albert-kam** [comment]
Your solution works. I can finally set OffsetDateTime.MAX to the valid_end.

Just want to share that i use infinity in the DDL, like this:

```
CREATE TABLE brands (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code CITEXT NOT NULL unique,
	name CITEXT NOT NULL unique,
	mutator_event_id INT REFERENCES event(id),
	valid_start TIMESTAMPTZ NOT NULL DEFAULT 'infinity'::timestamp,
	valid_end TIMESTAMPTZ NOT NULL DEFAULT 'infinity'::timestamp,
	oplock INT NOT NULL DEFAULT(0)
);
```
Where Infinity means 'not set or no value' yet. I was not sure whether NULL is a better choice to describe that meaning, because when i look at https://github.com/xocolatl/periods , i see that it uses infinity, and so i did. 

Thank you for listening and for your help !

**Comment by jnizet** [comment]
Glad to hear that.
